spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/gadgetarium
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: always
application:
  bucket:
    name:  gadgetarium-m4
cloud:
  aws:
    credentials:
      access-key: AKIA2HDIMUN7XHVDGAXA
      secret-key: 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

    region:
      static: eu-central-1
